#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

BASE_DIR=$( realpath $( dirname "${BASH_SOURCE[0]}" )/../ )

pushd "$BASE_DIR" 2>&1 >/dev/null

isort -c .
black --check .
flake8 .
pylint sxm tests

popd 2>&1 >/dev/null
